#!/bin/sh

ENV=${CI_ENVIRONMENT_SLUG:-unknown}
APP=${CI_PROJECT_PATH_SLUG:-unknown}
NS=${KUBE_NAMESPACE:-default}

echo "Environment: ${ENV}"
echo "Namespace  : ${NS}"

cat <<EOB > backend.tf # language=terraform
terraform {
  backend "http" {
  }
}
EOB

cat << EOC > details.auto.tfvars # language=terraform
environment = "${ENV}"
gitlab_app = "${APP}"

namespace = "${NS}"

bot_image = "$CI_REGISTRY_IMAGE"
EOC
