kind: ServiceAccount
apiVersion: v1
metadata:
  name: gitlab
  namespace: metalhead-zhong-xina
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab:cluster-admin
  namespace: metalhead-zhong-xina
roleRef:
  name: cluster-admin
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: metalhead-zhong-xina
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metalhead-zhong-xina:gitlab:view
roleRef:
  name: view
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gitlab
    namespace: metalhead-zhong-xina